=== epakai/hbr/handbrake_encode.dtd
<!ELEMENT handbrake_encode (handbrake_options, outfile+)>
<!ELEMENT handbrake_options (video, audio, picture, filters)>
<!ELEMENT video (video_encoder, quality)>
<!ELEMENT video_encoder (#PCDATA)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT audio (audio_encoder?, audio_bitrate?, audio_quality?)>
<!ELEMENT audio_encoder (#PCDATA)>
<!ELEMENT audio_bitrate (#PCDATA)>
<!ELEMENT audio_quality (#PCDATA)>
<!ELEMENT picture (crop, anamorphic)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT anamorphic (#PCDATA)>
<!ELEMENT filters (deinterlace, decomb, denoise)>
<!ELEMENT deinterlace (#PCDATA)>
<!ELEMENT decomb (#PCDATA)>
<!ELEMENT denoise (#PCDATA)>
<!ELEMENT outfile (type, source, name, year, season, episode_number, episode_name?, chapters, audio, audio_names?, subtitle?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT source (filename, dvdtitle)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT dvdtitle (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT season (#PCDATA)>
<!ELEMENT episode_number (#PCDATA)>
<!ELEMENT episode_name (#PCDATA)>
<!ELEMENT chapters (#PCDATA)>
<!ELEMENT audio_names (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>

=== epakai/hbr/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE handbrake_encode SYSTEM "handbrake_encode.dtd">
<handbrake_encode>
	<handbrake_options>
		<video>
			<video_encoder>x264</video_encoder> <!-- x264, x265, mpeg4, mpeg2, VP8, theora -->
			<quality>18</quality> <!-- varies by codec choice, see handbrake gui -->
		</video>
		<audio>
			<audio_encoder>fdk_aac</audio_encoder> <!-- av_aac, fdk_aac, fdk_haac, copy:aac, ac3, copy:ac3, copy:dts, 
											copy:dtshd, mp3, copy:mp3, vorbis, flac16, flac24, copy -->
			<audio_bitrate>192</audio_bitrate> <!-- kb/s -->
			<audio_quality></audio_quality> <!-- only supported for mp3 [10-0] with 10 being worst, vorbis [-2,10] with -2 worst -->
		</audio>
		<picture>
			<crop></crop> <!-- top:bottom:left:right -->
			<anamorphic>loose</anamorphic> <!-- strict, loose -->
		</picture>
		<filters>
			<!-- deinterlace and decome are mutually exclusive -->
			<deinterlace>none</deinterlace> <!-- fast, slow, slower, bob, default, none -->
			<decomb>default</decomb> <!-- fast, bob, default, none -->
			<denoise>none</denoise> <!-- ultralight, light, medium, strong, default, none -->
		</filters>
	</handbrake_options>
	
	<outfile>
		<type></type><!-- type may be series or movie -->
		<source>
			<filename></filename>
			<dvdtitle></dvdtitle>
		</source>
		<!-- filename depends on outfile type -->
		<!-- series filename: "<name> - s<season>e<episode_number> - <episode_name>" -->
		<!-- movie filename: "<name> (<year>) -->
		<name></name>
		<year></year>
		<season></season>
		<episode_number></episode_number>
		<episode_name></episode_name>

		<chapters></chapters> <!-- specified as a range "1-3" or single chapter "3" -->
		<audio></audio> <!-- comma separated list of audio tracks -->
		<audio_names></audio_names> <!-- comma separated list of track names if defaults are bad -->
		<subtitle></subtitle> <!-- comma separated list of subtitle tracks -->
	</outfile>
</handbrake_encode>

=== epakai/hbr/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE handbrake_encode SYSTEM "handbrake_encode.dtd">
	<handbrake_encode>
 <handbrake_options 
			video_encoder="x264"
 			quality="18"
 			audio_encoder="fdk_aac" 
 			audio_bitrate="192" 
			audio_quality=""
 			crop="3:3:3:3"
 			anamorphic="loose"
 			deinterlace="none"
			decomb="default"
 			denoise="none"
 />	<outfile>
 		<type></type><!-- type may be series or movie -->
		<source>
 			<filename>moya.iso</filename>
			<dvdtitle>5</dvdtitle>
 		</source>
		<!-- filename depends on outfile type -->
		<!-- series filename: "<name> - s<season>e<episode_number> - <episode_name>" -->
		<!-- movie filename: "<name> (<year>)" -->
		<name>Moya</name>
 		<year>1986</year>
 		<season>5</season>
		<episode_number></episode_number>
 		<episode_name></episode_name>
		<chapters></chapters> <!-- specified as a range "1-3" or single chapter "3" -->
		<audio></audio> <!-- comma separated list of audio tracks -->
		<audio_names></audio_names> <!-- comma separated list of track names if defaults are bad -->
		<subtitle></subtitle> <!-- comma separated list of subtitle tracks -->
	</outfile>
	<outfile>
 		<type></type>
		<source>
 			<filename>moya.iso</filename>
			<dvdtitle>5</dvdtitle>
 		</source>
		<name>Moya</name>
 		<year>1986</year>
 		<season>5</season>
		<episode_number></episode_number>
 		<episode_name></episode_name>
		<chapters></chapters>
		<audio></audio>
		<audio_names></audio_names>
		<subtitle></subtitle>
	</outfile>
	<outfile>
 		<type></type>
		<source>
 			<filename>moya.iso</filename>
			<dvdtitle>5</dvdtitle>
 		</source>
		<name>Moya</name>
 		<year>1986</year>
 		<season>5</season>
		<episode_number></episode_number>
 		<episode_name></episode_name>
		<chapters></chapters>
		<audio></audio>
		<audio_names></audio_names>
		<subtitle></subtitle>
	</outfile>
</handbrake_encode>
